[config]
skip_core_tasks = true

[env.release]
BUILD_OPTION = "--release"

[tasks.clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.build-binary]
private = true
workspace = false
command = "cargo"
args = ["build", "@@remove-empty(BUILD_OPTION)"]

[tasks.strip-binary]
private = true
workspace = false
condition = { profiles = ["release"] }
command = "strip"
args = ["./target/release/logdna-agent"]

[tasks.build]
workspace = false
dependencies = ["build-binary", "strip-binary"]

[tasks.build-flow]
workspace = false
dependencies = ["clean", "build"]

[tasks.format]
workspace = false
install_crate = { rustup_component_name = "rustfmt" }
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy]
workspace = false
command = "cargo"
install_crate = { rustup_component_name = "clippy" }
args = ["clippy", "--all-targets", "@@remove-empty(BUILD_OPTION)", "--", "-D", "warnings"]

[tasks.udeps]
workspace = false
install_crate = "cargo-udeps"
command = "cargo"
args = ["+nightly", "udeps", "--all-targets", "@@remove-empty(BUILD_OPTION)"]

[tasks.audit]
workspace = false
install_crate = "cargo-audit"
command = "cargo"
args = ["audit"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test", "@@remove-empty(BUILD_OPTION)"]

[tasks.test-flow]
workspace = false
dependencies = [
	"clean",
	"test"
]

[tasks.test-all-flow]
workspace = false
dependencies = [
	"clean",
	"format",
	"clippy",
	"udeps",
	"audit",
	"test"
]

