[package]
name = "k8s"
version = "0.1.0"
authors = ["CJP10 <connor.peticca@logdna.com>"]
edition = "2018"

[dependencies]
#local
middleware = { package = "middleware", path = "../middleware" }
http = { package = "http", path = "../http" }
metrics = { package = "metrics", path = "../metrics" }

crossbeam = "0.7"
regex = "1"
lazy_static = "1"
log = "0.4"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
quick-error = "1"
parking_lot = "0.9"
kube = "0.29.0"
k8s-openapi = { version = "0.7.1", default_features = false, features = ["v1_15"] }
serde_json = "1"
